[build]
  command = "ng build --configuration production"
  publish = "dist/bookmark-manager/browser"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200